.TH MYCAT 1 "September 2025" "Version 0.4.1" "User Commands"
.SH NAME
mycat \- display contents of a file on the terminal
.SH SYNOPSIS
mycat [FILE]
.SH DESCRIPTION
The mycat program reads a file and writes its contents to the standard output.
If no file is given, it reads from standard input.
.SH AUTHOR
Your Name fatimamliha024@gmail.com
